name: test
on:
  schedule:
    - cron: "10 14 1-31/2 * *"
  workflow_dispatch:
    
jobs:
  updates:
    name: Get-latest
    runs-on: ubuntu-latest
    steps:
      - name: get
        run: |
          list=$(
            curl -s -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/brave/brave-browser/releases/latest"
          ) 
          echo "$list" | jq -c '. | {date: .published_at, id: .id, prerelease: .prerelease, tag_name: .tag_name, name: .name}' > latest
          cat latest | jq -r .tag_name > tag 
          cat tag
          cat latest | jq -r .name | awk '{print $4}'  | awk -F '.' '{print $1}' > name
          cat name
          
          
                
                
              
              
              
          
