name: test
on:
  schedule:
    - cron: "10 14 1-31/2 * *"
  workflow_dispatch:
    
jobs:
  updates:
    name: Get-latest
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: get
        run: |
          list=$(
            curl -s -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/brave/brave-browser/releases/latest"
          ) 
          echo "$list" | jq -c '. | {date: .published_at, id: .id, prerelease: .prerelease, tag_name: .tag_name, name: .name}' > latest
          TAG=$(cat latest | jq -r .tag_name)
          echo "$TAG"
          #echo "VERSION=${TAG#v}"
          #echo "MAJOR=$(cat latest | jq -r .name | awk '{print $4}'  | awk -F '.' '{print $1}')"

          VERSION=${TAG#v}
          MAJOR=$(cat latest | jq -r .name | awk '{print $4}'  | awk -F '.' '{print $1}')
          sed -i -e 's/app.version = .*/app.version = '"${VERSION}"'/' -e 's/app.major = .*/app.major = '"${MAJOR}"'/' build.properties
      -
        name: Set up Git
        run: |
          git config user.name GitHub
          git config user.email noreply@github.com
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git
      -
        name: Commit and push changes
        run: |
          git add .
          git commit --author "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
          
                
                
              
              
              
          
